### ISSUE TITLE
Open Source?

### ISSUE THREAD

**Issue by franzen** [Optomatica/optobot#8]
If you want to be an open source project and get people to contribute, you should allow people to push their own branches. You can still protect "master" and possibly some other branches (eg "dev" for the latest development branch) so only you are allowed to modify them.

**Comment by mbeltagy** [comment]
We follow the fork/pull request model. Active contributors will be given direct right access to the repo.

We will shortly add a guide to contributors to clear any confusion.

**Comment by franzen** [comment]
@mbeltagy You are ofc right.  In my mind, I was restricted to how we handle GH at work. I'm closing this now.
